
sonata_user:
    security_acl: true
    manager_type: orm # can be orm or mongodb
    class:
        user:  Kdig\UserBundle\Entity\User
        group: Kdig\UserBundle\Entity\Group
        
    profile:  # Profile Form (firstname, lastname, etc ...)
        form:
            type:               sonata_user_profile
            handler:            sonata.user.profile.form.handler.default
            name:               sonata_user_profile_form
            validation_groups:  [Profile]