parameters:
#    kdig_archaeological.example.class: Kdig\ArchaeologicalBundle\Example

services:
#    kdig_archaeological.example:
#        class: %kdig_archaeological.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
