parameters:
#    kdig_archaeological.example.class: Kdig\ArchaeologicalBundle\Example

services:
  ## post pre update event after persist object
  orient.pottery.listener:
      class: 'Kdig\ArchaeologicalBundle\Listener\UsListener'
      arguments: [ '@service_container' ]
      tags:
          - { name: doctrine.event_listener, event: postUpdate, method: postUpdate }
          - { name: doctrine.event_listener, event: postPersist, method: postPersist }